/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    markets: Market;
    applications: Application;
    waitlists: Waitlist;
    'intelligence-briefs': IntelligenceBrief;
    categories: Category;
    authors: Author;
    articles: Article;
    'injured-leads': InjuredLead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    waitlists: WaitlistsSelect<false> | WaitlistsSelect<true>;
    'intelligence-briefs': IntelligenceBriefsSelect<false> | IntelligenceBriefsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'injured-leads': InjuredLeadsSelect<false> | InjuredLeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'markets-page': MarketsPage;
    'site-settings': SiteSetting;
    'header-nav': HeaderNav;
    'footer-nav': FooterNav;
  };
  globalsSelect: {
    'markets-page': MarketsPageSelect<false> | MarketsPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-nav': HeaderNavSelect<false> | HeaderNavSelect<true>;
    'footer-nav': FooterNavSelect<false> | FooterNavSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: string;
  metro: string;
  /**
   * URL-friendly name. Used in /markets/[slug]
   */
  slug: string;
  state: string;
  status: 'active' | 'limited' | 'capped' | 'evaluation';
  mii: number;
  casesAcquiredYearly: number;
  partnersActive: number;
  maxPartners: number;
  /**
   * Current number of firms on the waitlist for this market.
   */
  waitlistPosition?: number | null;
  population: string;
  monthlySearchVolume: string;
  responseTime: string;
  activatedDate: string;
  avgSettlement: string;
  avgCaseValue: string;
  heroHeadline: string;
  heroSubline: string;
  testimonial?: {
    quote?: string | null;
    author?: string | null;
  };
  whyThisMarket?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Hidden semantic blocks for Answer Engine Optimization. Will be rendered seamlessly.
   */
  aeoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  firmName: string;
  fullName: string;
  title: string;
  workEmail: string;
  phone: string;
  website: string;
  linkedIn?: string | null;
  leadScore: number;
  leadTier: 'platinum' | 'gold' | 'silver' | 'disqualified';
  status: 'pending' | 'approved' | 'rejected' | 'waitlisted';
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists".
 */
export interface Waitlist {
  id: string;
  email: string;
  firmName?: string | null;
  hardStopReason?: string | null;
  referralEmail?: string | null;
  source?: ('waitlist' | 'intelligence') | null;
  role?: ('owner' | 'partner' | 'intake' | 'ops' | 'other') | null;
  market?:
    | (
        | 'personal-injury'
        | 'workers-comp'
        | 'medical-malpractice'
        | 'product-liability'
        | 'premises-liability'
        | 'auto-accidents'
        | 'other'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subscribers to the CasePort Intelligence weekly brief.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intelligence-briefs".
 */
export interface IntelligenceBrief {
  id: string;
  /**
   * Subscriber work email address.
   */
  email: string;
  role: 'owner' | 'partner' | 'intake' | 'ops' | 'other';
  market:
    | 'personal-injury'
    | 'workers-comp'
    | 'medical-malpractice'
    | 'product-liability'
    | 'premises-liability'
    | 'auto-accidents'
    | 'other';
  status?: ('active' | 'unsubscribed') | null;
  /**
   * Checked once an admin has viewed this subscriber.
   */
  seen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  title: string;
  avatar?: (string | null) | Media;
  bio?: string | null;
  profileUrl?: string | null;
  /**
   * Short labels shown as pills on article pages (e.g. "Expert", "50+ Firms").
   */
  badges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stats shown in the credential grid (e.g. value "50+" / label "Firms Advised").
   */
  credentials?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Action buttons shown in the author bio section (e.g. "Ask a Question", "View Profile").
   */
  ctaButtons?:
    | {
        label: string;
        href: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('twitter' | 'linkedin' | 'github') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  /**
   * 50-80 chars. Auto slug.
   */
  title?: string | null;
  /**
   * Live reading now counter
   */
  currentReaders?: number | null;
  /**
   * Cited by X firms
   */
  citationCount?: number | null;
  /**
   * Signal Strength (0-100)
   */
  signalStrength?: number | null;
  slug?: string | null;
  author?: (string | null) | Author;
  category?: (string | null) | Category;
  contentFormat?:
    | (
        | 'Pillar Page'
        | 'Cluster Article'
        | 'FAQ Article'
        | 'How-To Guide'
        | 'News'
        | 'Research Report'
        | 'Case Study'
        | 'Comparison'
        | 'Definition'
      )
    | null;
  heroImage?: (string | null) | Media;
  excerpt?: string | null;
  subtitle?: string | null;
  executiveSummary?: string | null;
  keyTakeaways?:
    | {
        point?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Customizable Table with editable headers and rows for ROI matrix.
   */
  roiTable: {
    enableTable?: boolean | null;
    tableName?: string | null;
    headers: {
      col1: string;
      col2: string;
      col3: string;
      col4: string;
      col5: string;
    };
    rows?:
      | {
          col1: string;
          col2: string;
          col3: string;
          col4: string;
          col5: string;
          id?: string | null;
        }[]
      | null;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedArticles?: (string | Article)[] | null;
  focusKeyword?: string | null;
  keywordDifficulty?: number | null;
  monthlySearchVolume?: number | null;
  currentRankingPosition?: number | null;
  secondaryKeywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  canonicalUrl?: string | null;
  socialHeadline?: string | null;
  socialDescription?: string | null;
  socialShareImage?: (string | null) | Media;
  xCardType?: ('summary_large_image' | 'summary') | null;
  xCardTitle?: string | null;
  xCardDescription?: string | null;
  xCardImage?: (string | null) | Media;
  competingUrl?: string | null;
  contentGap?:
    | {
        gap?: string | null;
        id?: string | null;
      }[]
    | null;
  directAnswer?: string | null;
  aiCitationSummary?: string | null;
  primaryAiQuery?: string | null;
  keyStatistics?:
    | {
        text: string;
        sourceName: string;
        sourceUrl?: string | null;
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  faqSection?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  termDefinitions?:
    | {
        term: string;
        definition: string;
        isProprietary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  expertQuotes?:
    | {
        quote: string;
        speakerName: string;
        credentials?: string | null;
        id?: string | null;
      }[]
    | null;
  voiceAnswer?: string | null;
  speakableCssSelectors?:
    | {
        selector?: string | null;
        id?: string | null;
      }[]
    | null;
  conversationalQueryVariants?:
    | {
        query?: string | null;
        id?: string | null;
      }[]
    | null;
  targetsSpecificLocation?: boolean | null;
  locationTargets?:
    | {
        state?: string | null;
        city?: string | null;
        id?: string | null;
      }[]
    | null;
  schemaType?: ('Article' | 'FAQPage' | 'HowTo' | 'NewsArticle' | 'LegalScholarlyArticle') | null;
  howToSteps?:
    | {
        name?: string | null;
        description?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  sameAsEntityUrls?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  articleSection?: string | null;
  apaCitation?: string | null;
  customJsonLd?: string | null;
  legalDisclaimer?: ('Standard' | 'No Legal Advice' | 'CasePort Platform' | 'None') | null;
  abaComplianceVerified?: boolean | null;
  expertReviewer?: string | null;
  externalSources?:
    | {
        name: string;
        url?: string | null;
        credibilityTier?: ('High' | 'Medium' | 'Low') | null;
        id?: string | null;
      }[]
    | null;
  pressMentions?:
    | {
        source?: string | null;
        url?: string | null;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaOverride?: {
    heading?: string | null;
    body?: string | null;
    primaryLabel?: string | null;
    primaryUrl?: string | null;
    secondaryLabel?: string | null;
    secondaryUrl?: string | null;
  };
  contentUpdateHistory?:
    | {
        date: string;
        summary: string;
        updatedBy: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Select all states this article targets
   */
  targetStates?:
    | (
        | 'AL'
        | 'AK'
        | 'AZ'
        | 'AR'
        | 'CA'
        | 'CO'
        | 'CT'
        | 'DE'
        | 'FL'
        | 'GA'
        | 'HI'
        | 'ID'
        | 'IL'
        | 'IN'
        | 'IA'
        | 'KS'
        | 'KY'
        | 'LA'
        | 'ME'
        | 'MD'
        | 'MA'
        | 'MI'
        | 'MN'
        | 'MS'
        | 'MO'
        | 'MT'
        | 'NE'
        | 'NV'
        | 'NH'
        | 'NJ'
        | 'NM'
        | 'NY'
        | 'NC'
        | 'ND'
        | 'OH'
        | 'OK'
        | 'OR'
        | 'PA'
        | 'RI'
        | 'SC'
        | 'SD'
        | 'TN'
        | 'TX'
        | 'UT'
        | 'VT'
        | 'VA'
        | 'WA'
        | 'WV'
        | 'WI'
        | 'WY'
      )[]
    | null;
  targetCities?:
    | {
        city?: string | null;
        state?: string | null;
        id?: string | null;
      }[]
    | null;
  jurisdiction?: string | null;
  serviceAreaDescription?: string | null;
  localSchemaType?: ('LocalBusiness' | 'Attorney' | 'ServiceArea') | null;
  stateSpecificDeadline?: number | null;
  stateSpecificExceptions?: string | null;
  tollingProvisions?:
    | {
        state?: string | null;
        tollingRule?: string | null;
        id?: string | null;
      }[]
    | null;
  sgeAnswerability?: number | null;
  /**
   * Direct, extractable answer for Google SGE
   */
  sgeOptimizedAnswer?: string | null;
  uniqueContentSignals?:
    | {
        signal?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  freshnessSignal?: ('breaking' | 'recent' | 'evergreen') | null;
  competitorComparison?: string | null;
  dominanceScoring?: {
    seoScore?: number | null;
    aeoScore?: number | null;
    geoScore?: number | null;
    sgeScore?: number | null;
    voiceSearchScore?: number | null;
    overallDominanceScore?: number | null;
    dominanceRank?: ('critical' | 'weak' | 'strong' | 'dominant') | null;
    competitiveAdvantageScore?: number | null;
  };
  topCompetitors?:
    | {
        url?: string | null;
        estimatedScore?: number | null;
        yourAdvantage?: string | null;
        id?: string | null;
      }[]
    | null;
  competitiveGapAnalysis?: string | null;
  uniqueAdvantages?:
    | {
        advantage?: string | null;
        id?: string | null;
      }[]
    | null;
  performanceMetrics?: {
    totalFormSubmissions?: number | null;
    totalEmailCaptures?: number | null;
    averageLeadQualityScore?: number | null;
    leadToCaseConversionRate?: number | null;
    estimatedRevenue?: number | null;
    estimatedProfit?: number | null;
    roi?: number | null;
    performanceStatus?: ('loss' | 'breakeven' | 'profitable' | 'highly_profitable') | null;
    recommendedAction?: ('remove' | 'optimize' | 'maintain' | 'expand') | null;
  };
  searchEngineSubmission?: {
    googleSubmitted?: boolean | null;
    googleSubmissionTime?: string | null;
    googleSubmissionMessage?: string | null;
    bingSubmitted?: boolean | null;
    bingSubmissionTime?: string | null;
    bingSubmissionMessage?: string | null;
  };
  primaryEntity?: string | null;
  entityDefinition?: string | null;
  relatedEntities?:
    | {
        entity?: string | null;
        id?: string | null;
      }[]
    | null;
  entityImportance?: ('critical' | 'important' | 'supporting') | null;
  contentValidation?: {
    contentLength?: number | null;
    h2Count?: number | null;
    h3Count?: number | null;
    faqCount?: number | null;
    validationStatus?: ('pass' | 'warning' | 'fail') | null;
    validationErrors?:
      | {
          error?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  internalLinks?:
    | {
        linkedArticleId?: (string | null) | Article;
        anchorText?: string | null;
        relevanceScore?: number | null;
        id?: string | null;
      }[]
    | null;
  contentFreshness?: {
    lastReviewDate?: string | null;
    nextReviewDue?: string | null;
    daysOld?: number | null;
    freshnessStatus?: ('fresh' | 'current' | 'aging' | 'stale') | null;
  };
  featuredSnippetOptimization?: {
    targetSnippetType?: ('paragraph' | 'list' | 'table' | 'definition') | null;
    /**
     * Content optimized for featured snippet
     */
    snippetContent?: string | null;
    /**
     * Position in Google featured snippets (if ranked)
     */
    currentSnippetRank?: number | null;
    snippetOptimizationScore?: number | null;
  };
  backlinkTracking?: {
    totalBacklinks?: number | null;
    highQualityBacklinks?: number | null;
    referringDomains?: number | null;
    backlinkGrowth?: number | null;
    backlinkLastUpdated?: string | null;
  };
  keywordRankings?:
    | {
        keyword?: string | null;
        currentRank?: number | null;
        previousRank?: number | null;
        rankChange?: number | null;
        searchVolume?: number | null;
        lastUpdated?: string | null;
        id?: string | null;
      }[]
    | null;
  trafficMetrics?: {
    monthlyVisitors?: number | null;
    bounceRate?: number | null;
    averageTimeOnPage?: number | null;
    scrollDepth?: number | null;
    trafficSources?:
      | {
          source?: string | null;
          visitors?: number | null;
          percentage?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  aiCitationTracking?: {
    claudeCitations?: number | null;
    chatgptCitations?: number | null;
    perplexityCitations?: number | null;
    totalAiCitations?: number | null;
    shareOfVoice?: number | null;
    lastUpdated?: string | null;
  };
  conversionFunnel?: {
    uniqueVisitors?: number | null;
    formViews?: number | null;
    formSubmissions?: number | null;
    emailCaptures?: number | null;
    confirmedLeads?: number | null;
    confirmedCases?: number | null;
    visitorToFormRate?: number | null;
    formToLeadRate?: number | null;
    leadToCaseRate?: number | null;
  };
  /**
   * Date the article was published
   */
  publishedDate?: string | null;
  /**
   * Last time this article was saved
   */
  updatedAt: string;
  aeoScore?: number | null;
  /**
   * Auto-calculated on every save. 0-100. Target 80+ before publishing.
   */
  seoScore?: number | null;
  readTime?: number | null;
  searchIntent?: ('Informational' | 'Commercial Investigation' | 'Transactional' | 'Navigational') | null;
  targetSerpFeature?: string | null;
  contentConfidence?: ('High' | 'Medium' | 'Low') | null;
  hideFromSearchEngines?: boolean | null;
  reviewCycle?: ('3months' | '6months' | '12months' | 'evergreen') | null;
  nextReviewDue?: string | null;
  lastFactVerified?: string | null;
  contentQualityScore?: number | null;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "injured-leads".
 */
export interface InjuredLead {
  id: string;
  firstName: string;
  lastName: string;
  phone: string;
  email?: string | null;
  accidentDate?: string | null;
  state?: string | null;
  county?: string | null;
  accidentType?: string | null;
  role?: string | null;
  medicalCare?: string | null;
  fault?: string | null;
  otherPartyInsurance?: string | null;
  hasLawyer?: string | null;
  preferredContact?: string | null;
  canTalkNow?: string | null;
  hasDocuments?: string | null;
  seen?: boolean | null;
  /**
   * Documents explicitly uploaded by the user during this form submission.
   */
  uploadedDocuments?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'markets';
        value: string | Market;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'waitlists';
        value: string | Waitlist;
      } | null)
    | ({
        relationTo: 'intelligence-briefs';
        value: string | IntelligenceBrief;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'injured-leads';
        value: string | InjuredLead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  metro?: T;
  slug?: T;
  state?: T;
  status?: T;
  mii?: T;
  casesAcquiredYearly?: T;
  partnersActive?: T;
  maxPartners?: T;
  waitlistPosition?: T;
  population?: T;
  monthlySearchVolume?: T;
  responseTime?: T;
  activatedDate?: T;
  avgSettlement?: T;
  avgCaseValue?: T;
  heroHeadline?: T;
  heroSubline?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
      };
  whyThisMarket?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  aeoContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  firmName?: T;
  fullName?: T;
  title?: T;
  workEmail?: T;
  phone?: T;
  website?: T;
  linkedIn?: T;
  leadScore?: T;
  leadTier?: T;
  status?: T;
  answers?: T;
  seen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists_select".
 */
export interface WaitlistsSelect<T extends boolean = true> {
  email?: T;
  firmName?: T;
  hardStopReason?: T;
  referralEmail?: T;
  source?: T;
  role?: T;
  market?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intelligence-briefs_select".
 */
export interface IntelligenceBriefsSelect<T extends boolean = true> {
  email?: T;
  role?: T;
  market?: T;
  status?: T;
  seen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  avatar?: T;
  bio?: T;
  profileUrl?: T;
  badges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  credentials?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  currentReaders?: T;
  citationCount?: T;
  signalStrength?: T;
  slug?: T;
  author?: T;
  category?: T;
  contentFormat?: T;
  heroImage?: T;
  excerpt?: T;
  subtitle?: T;
  executiveSummary?: T;
  keyTakeaways?:
    | T
    | {
        point?: T;
        id?: T;
      };
  roiTable?:
    | T
    | {
        enableTable?: T;
        tableName?: T;
        headers?:
          | T
          | {
              col1?: T;
              col2?: T;
              col3?: T;
              col4?: T;
              col5?: T;
            };
        rows?:
          | T
          | {
              col1?: T;
              col2?: T;
              col3?: T;
              col4?: T;
              col5?: T;
              id?: T;
            };
      };
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedArticles?: T;
  focusKeyword?: T;
  keywordDifficulty?: T;
  monthlySearchVolume?: T;
  currentRankingPosition?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  canonicalUrl?: T;
  socialHeadline?: T;
  socialDescription?: T;
  socialShareImage?: T;
  xCardType?: T;
  xCardTitle?: T;
  xCardDescription?: T;
  xCardImage?: T;
  competingUrl?: T;
  contentGap?:
    | T
    | {
        gap?: T;
        id?: T;
      };
  directAnswer?: T;
  aiCitationSummary?: T;
  primaryAiQuery?: T;
  keyStatistics?:
    | T
    | {
        text?: T;
        sourceName?: T;
        sourceUrl?: T;
        year?: T;
        id?: T;
      };
  faqSection?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  termDefinitions?:
    | T
    | {
        term?: T;
        definition?: T;
        isProprietary?: T;
        id?: T;
      };
  expertQuotes?:
    | T
    | {
        quote?: T;
        speakerName?: T;
        credentials?: T;
        id?: T;
      };
  voiceAnswer?: T;
  speakableCssSelectors?:
    | T
    | {
        selector?: T;
        id?: T;
      };
  conversationalQueryVariants?:
    | T
    | {
        query?: T;
        id?: T;
      };
  targetsSpecificLocation?: T;
  locationTargets?:
    | T
    | {
        state?: T;
        city?: T;
        id?: T;
      };
  schemaType?: T;
  howToSteps?:
    | T
    | {
        name?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  sameAsEntityUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  articleSection?: T;
  apaCitation?: T;
  customJsonLd?: T;
  legalDisclaimer?: T;
  abaComplianceVerified?: T;
  expertReviewer?: T;
  externalSources?:
    | T
    | {
        name?: T;
        url?: T;
        credibilityTier?: T;
        id?: T;
      };
  pressMentions?:
    | T
    | {
        source?: T;
        url?: T;
        date?: T;
        id?: T;
      };
  ctaOverride?:
    | T
    | {
        heading?: T;
        body?: T;
        primaryLabel?: T;
        primaryUrl?: T;
        secondaryLabel?: T;
        secondaryUrl?: T;
      };
  contentUpdateHistory?:
    | T
    | {
        date?: T;
        summary?: T;
        updatedBy?: T;
        id?: T;
      };
  targetStates?: T;
  targetCities?:
    | T
    | {
        city?: T;
        state?: T;
        id?: T;
      };
  jurisdiction?: T;
  serviceAreaDescription?: T;
  localSchemaType?: T;
  stateSpecificDeadline?: T;
  stateSpecificExceptions?: T;
  tollingProvisions?:
    | T
    | {
        state?: T;
        tollingRule?: T;
        id?: T;
      };
  sgeAnswerability?: T;
  sgeOptimizedAnswer?: T;
  uniqueContentSignals?:
    | T
    | {
        signal?: T;
        description?: T;
        id?: T;
      };
  freshnessSignal?: T;
  competitorComparison?: T;
  dominanceScoring?:
    | T
    | {
        seoScore?: T;
        aeoScore?: T;
        geoScore?: T;
        sgeScore?: T;
        voiceSearchScore?: T;
        overallDominanceScore?: T;
        dominanceRank?: T;
        competitiveAdvantageScore?: T;
      };
  topCompetitors?:
    | T
    | {
        url?: T;
        estimatedScore?: T;
        yourAdvantage?: T;
        id?: T;
      };
  competitiveGapAnalysis?: T;
  uniqueAdvantages?:
    | T
    | {
        advantage?: T;
        id?: T;
      };
  performanceMetrics?:
    | T
    | {
        totalFormSubmissions?: T;
        totalEmailCaptures?: T;
        averageLeadQualityScore?: T;
        leadToCaseConversionRate?: T;
        estimatedRevenue?: T;
        estimatedProfit?: T;
        roi?: T;
        performanceStatus?: T;
        recommendedAction?: T;
      };
  searchEngineSubmission?:
    | T
    | {
        googleSubmitted?: T;
        googleSubmissionTime?: T;
        googleSubmissionMessage?: T;
        bingSubmitted?: T;
        bingSubmissionTime?: T;
        bingSubmissionMessage?: T;
      };
  primaryEntity?: T;
  entityDefinition?: T;
  relatedEntities?:
    | T
    | {
        entity?: T;
        id?: T;
      };
  entityImportance?: T;
  contentValidation?:
    | T
    | {
        contentLength?: T;
        h2Count?: T;
        h3Count?: T;
        faqCount?: T;
        validationStatus?: T;
        validationErrors?:
          | T
          | {
              error?: T;
              id?: T;
            };
      };
  internalLinks?:
    | T
    | {
        linkedArticleId?: T;
        anchorText?: T;
        relevanceScore?: T;
        id?: T;
      };
  contentFreshness?:
    | T
    | {
        lastReviewDate?: T;
        nextReviewDue?: T;
        daysOld?: T;
        freshnessStatus?: T;
      };
  featuredSnippetOptimization?:
    | T
    | {
        targetSnippetType?: T;
        snippetContent?: T;
        currentSnippetRank?: T;
        snippetOptimizationScore?: T;
      };
  backlinkTracking?:
    | T
    | {
        totalBacklinks?: T;
        highQualityBacklinks?: T;
        referringDomains?: T;
        backlinkGrowth?: T;
        backlinkLastUpdated?: T;
      };
  keywordRankings?:
    | T
    | {
        keyword?: T;
        currentRank?: T;
        previousRank?: T;
        rankChange?: T;
        searchVolume?: T;
        lastUpdated?: T;
        id?: T;
      };
  trafficMetrics?:
    | T
    | {
        monthlyVisitors?: T;
        bounceRate?: T;
        averageTimeOnPage?: T;
        scrollDepth?: T;
        trafficSources?:
          | T
          | {
              source?: T;
              visitors?: T;
              percentage?: T;
              id?: T;
            };
      };
  aiCitationTracking?:
    | T
    | {
        claudeCitations?: T;
        chatgptCitations?: T;
        perplexityCitations?: T;
        totalAiCitations?: T;
        shareOfVoice?: T;
        lastUpdated?: T;
      };
  conversionFunnel?:
    | T
    | {
        uniqueVisitors?: T;
        formViews?: T;
        formSubmissions?: T;
        emailCaptures?: T;
        confirmedLeads?: T;
        confirmedCases?: T;
        visitorToFormRate?: T;
        formToLeadRate?: T;
        leadToCaseRate?: T;
      };
  publishedDate?: T;
  updatedAt?: T;
  aeoScore?: T;
  seoScore?: T;
  readTime?: T;
  searchIntent?: T;
  targetSerpFeature?: T;
  contentConfidence?: T;
  hideFromSearchEngines?: T;
  reviewCycle?: T;
  nextReviewDue?: T;
  lastFactVerified?: T;
  contentQualityScore?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "injured-leads_select".
 */
export interface InjuredLeadsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  email?: T;
  accidentDate?: T;
  state?: T;
  county?: T;
  accidentType?: T;
  role?: T;
  medicalCare?: T;
  fault?: T;
  otherPartyInsurance?: T;
  hasLawyer?: T;
  preferredContact?: T;
  canTalkNow?: T;
  hasDocuments?: T;
  seen?: T;
  uploadedDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets-page".
 */
export interface MarketsPage {
  id: string;
  /**
   * These FAQs will appear at the bottom of the main Markets hub page.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide defaults: SEO, CTAs, contact info, legal, and organization schema.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogImage?: (string | null) | Media;
  /**
   * Relative paths to prevent indexing (e.g. /thank-you)
   */
  noindexPages?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  injuredCtaLabel?: string | null;
  injuredCtaHref?: string | null;
  contactEmail?: string | null;
  brandName?: string | null;
  brandTagline?: string | null;
  brandSummary?: string | null;
  legalDisclaimer?: string | null;
  privacyPolicyUrl?: string | null;
  termsUrl?: string | null;
  orgName?: string | null;
  orgUrl?: string | null;
  orgDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the top navigation links and the primary CTA button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav".
 */
export interface HeaderNav {
  id: string;
  /**
   * Order determines display order in the navigation.
   */
  navLinks?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls footer nav groups, social links, and utility links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-nav".
 */
export interface FooterNav {
  id: string;
  platformLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  resourceLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets-page_select".
 */
export interface MarketsPageSelect<T extends boolean = true> {
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  noindexPages?:
    | T
    | {
        path?: T;
        id?: T;
      };
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  injuredCtaLabel?: T;
  injuredCtaHref?: T;
  contactEmail?: T;
  brandName?: T;
  brandTagline?: T;
  brandSummary?: T;
  legalDisclaimer?: T;
  privacyPolicyUrl?: T;
  termsUrl?: T;
  orgName?: T;
  orgUrl?: T;
  orgDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav_select".
 */
export interface HeaderNavSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-nav_select".
 */
export interface FooterNavSelect<T extends boolean = true> {
  platformLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  resourceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}