/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    markets: Market;
    applications: Application;
    waitlists: Waitlist;
    'intelligence-briefs': IntelligenceBrief;
    categories: Category;
    authors: Author;
    articles: Article;
    'injured-leads': InjuredLead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    waitlists: WaitlistsSelect<false> | WaitlistsSelect<true>;
    'intelligence-briefs': IntelligenceBriefsSelect<false> | IntelligenceBriefsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'injured-leads': InjuredLeadsSelect<false> | InjuredLeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'markets-page': MarketsPage;
    'site-settings': SiteSetting;
    'header-nav': HeaderNav;
    'footer-nav': FooterNav;
  };
  globalsSelect: {
    'markets-page': MarketsPageSelect<false> | MarketsPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-nav': HeaderNavSelect<false> | HeaderNavSelect<true>;
    'footer-nav': FooterNavSelect<false> | FooterNavSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: string;
  metro: string;
  /**
   * URL-friendly name. Used in /markets/[slug]
   */
  slug: string;
  state: string;
  status: 'active' | 'limited' | 'capped' | 'evaluation';
  mii: number;
  casesAcquiredYearly: number;
  partnersActive: number;
  maxPartners: number;
  /**
   * Current number of firms on the waitlist for this market.
   */
  waitlistPosition?: number | null;
  population: string;
  monthlySearchVolume: string;
  responseTime: string;
  activatedDate: string;
  avgSettlement: string;
  avgCaseValue: string;
  heroHeadline: string;
  heroSubline: string;
  testimonial?: {
    quote?: string | null;
    author?: string | null;
  };
  whyThisMarket?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Hidden semantic blocks for Answer Engine Optimization. Will be rendered seamlessly.
   */
  aeoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  firmName: string;
  fullName: string;
  title: string;
  workEmail: string;
  phone: string;
  website: string;
  linkedIn?: string | null;
  leadScore: number;
  leadTier: 'platinum' | 'gold' | 'silver' | 'disqualified';
  status: 'pending' | 'approved' | 'rejected' | 'waitlisted';
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists".
 */
export interface Waitlist {
  id: string;
  email: string;
  firmName?: string | null;
  hardStopReason?: string | null;
  referralEmail?: string | null;
  source?: ('waitlist' | 'intelligence') | null;
  role?: ('owner' | 'partner' | 'intake' | 'ops' | 'other') | null;
  market?:
    | (
        | 'personal-injury'
        | 'workers-comp'
        | 'medical-malpractice'
        | 'product-liability'
        | 'premises-liability'
        | 'auto-accidents'
        | 'other'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subscribers to the CasePort Intelligence weekly brief.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intelligence-briefs".
 */
export interface IntelligenceBrief {
  id: string;
  /**
   * Subscriber work email address.
   */
  email: string;
  role: 'owner' | 'partner' | 'intake' | 'ops' | 'other';
  market:
    | 'personal-injury'
    | 'workers-comp'
    | 'medical-malpractice'
    | 'product-liability'
    | 'premises-liability'
    | 'auto-accidents'
    | 'other';
  status?: ('active' | 'unsubscribed') | null;
  /**
   * Checked once an admin has viewed this subscriber.
   */
  seen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  title: string;
  avatar?: (string | null) | Media;
  bio?: string | null;
  profileUrl?: string | null;
  /**
   * Short labels shown as pills on article pages (e.g. "Expert", "50+ Firms").
   */
  badges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Stats shown in the credential grid (e.g. value "50+" / label "Firms Advised").
   */
  credentials?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('twitter' | 'linkedin' | 'github') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  slug: string;
  heroImage: string | Media;
  category: string | Category;
  author: string | Author;
  /**
   * Estimated reading time in minutes
   */
  readTime?: number | null;
  publishedAt?: string | null;
  excerpt: string;
  /**
   * Displayed directly under the main title in the hero section.
   */
  subtitle?: string | null;
  /**
   * A larger editorial intro text bridging the hero and the main body.
   */
  executiveSummary?: string | null;
  /**
   * Bullet points summarizing the article, displayed in a highlighted box.
   */
  keyTakeaways?:
    | {
        takeaway: string;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Structured answers to feed directly to AI search engines (ChatGPT, Google AI Overview). Hidden from visual reading view.
   */
  seoAnswers?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * These populate the FAQ accordion at the bottom of the article.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  relatedArticles?: (string | Article)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "injured-leads".
 */
export interface InjuredLead {
  id: string;
  firstName: string;
  lastName: string;
  phone: string;
  email?: string | null;
  accidentDate?: string | null;
  state?: string | null;
  county?: string | null;
  accidentType?: string | null;
  role?: string | null;
  medicalCare?: string | null;
  fault?: string | null;
  otherPartyInsurance?: string | null;
  hasLawyer?: string | null;
  preferredContact?: string | null;
  canTalkNow?: string | null;
  hasDocuments?: string | null;
  seen?: boolean | null;
  /**
   * Documents explicitly uploaded by the user during this form submission.
   */
  uploadedDocuments?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'markets';
        value: string | Market;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'waitlists';
        value: string | Waitlist;
      } | null)
    | ({
        relationTo: 'intelligence-briefs';
        value: string | IntelligenceBrief;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'injured-leads';
        value: string | InjuredLead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  metro?: T;
  slug?: T;
  state?: T;
  status?: T;
  mii?: T;
  casesAcquiredYearly?: T;
  partnersActive?: T;
  maxPartners?: T;
  waitlistPosition?: T;
  population?: T;
  monthlySearchVolume?: T;
  responseTime?: T;
  activatedDate?: T;
  avgSettlement?: T;
  avgCaseValue?: T;
  heroHeadline?: T;
  heroSubline?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
      };
  whyThisMarket?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  aeoContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  firmName?: T;
  fullName?: T;
  title?: T;
  workEmail?: T;
  phone?: T;
  website?: T;
  linkedIn?: T;
  leadScore?: T;
  leadTier?: T;
  status?: T;
  answers?: T;
  seen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlists_select".
 */
export interface WaitlistsSelect<T extends boolean = true> {
  email?: T;
  firmName?: T;
  hardStopReason?: T;
  referralEmail?: T;
  source?: T;
  role?: T;
  market?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intelligence-briefs_select".
 */
export interface IntelligenceBriefsSelect<T extends boolean = true> {
  email?: T;
  role?: T;
  market?: T;
  status?: T;
  seen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  avatar?: T;
  bio?: T;
  profileUrl?: T;
  badges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  credentials?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  category?: T;
  author?: T;
  readTime?: T;
  publishedAt?: T;
  excerpt?: T;
  subtitle?: T;
  executiveSummary?: T;
  keyTakeaways?:
    | T
    | {
        takeaway?: T;
        id?: T;
      };
  content?: T;
  seoAnswers?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedArticles?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "injured-leads_select".
 */
export interface InjuredLeadsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  email?: T;
  accidentDate?: T;
  state?: T;
  county?: T;
  accidentType?: T;
  role?: T;
  medicalCare?: T;
  fault?: T;
  otherPartyInsurance?: T;
  hasLawyer?: T;
  preferredContact?: T;
  canTalkNow?: T;
  hasDocuments?: T;
  seen?: T;
  uploadedDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets-page".
 */
export interface MarketsPage {
  id: string;
  /**
   * These FAQs will appear at the bottom of the main Markets hub page.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide defaults: SEO, CTAs, contact info, legal, and organization schema.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  ogImage?: (string | null) | Media;
  /**
   * Relative paths to prevent indexing (e.g. /thank-you)
   */
  noindexPages?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  injuredCtaLabel?: string | null;
  injuredCtaHref?: string | null;
  contactEmail?: string | null;
  brandName?: string | null;
  brandTagline?: string | null;
  brandSummary?: string | null;
  legalDisclaimer?: string | null;
  privacyPolicyUrl?: string | null;
  termsUrl?: string | null;
  orgName?: string | null;
  orgUrl?: string | null;
  orgDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the top navigation links and the primary CTA button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav".
 */
export interface HeaderNav {
  id: string;
  /**
   * Order determines display order in the navigation.
   */
  navLinks?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls footer nav groups, social links, and utility links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-nav".
 */
export interface FooterNav {
  id: string;
  platformLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  resourceLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets-page_select".
 */
export interface MarketsPageSelect<T extends boolean = true> {
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  noindexPages?:
    | T
    | {
        path?: T;
        id?: T;
      };
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  injuredCtaLabel?: T;
  injuredCtaHref?: T;
  contactEmail?: T;
  brandName?: T;
  brandTagline?: T;
  brandSummary?: T;
  legalDisclaimer?: T;
  privacyPolicyUrl?: T;
  termsUrl?: T;
  orgName?: T;
  orgUrl?: T;
  orgDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav_select".
 */
export interface HeaderNavSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-nav_select".
 */
export interface FooterNavSelect<T extends boolean = true> {
  platformLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  resourceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}